# set docker compose file version
version: '3.9'
services:
  blog-database:
    #image
    image: mongo
    #set the ports
    ports:
      - '27017:27017'
  blog-backend:
    #docker image file
    build: backend/
    #environment
    environment:
      - PORT=3001
      #use local database name (running inside codespace, rather than docker internal)
      - DATABASE_URL=mongodb://blog-database:27017/blog
        #docker compose will automatically map the URL to the correct path
    ports:
      - '3001:3001'
    depends_on:
      - blog-database
  blog-frontend:
    build:
      context: .
      args:
        #set the backend to match above
        #use code-space URL for this project
        VITE_BACKEND_URL: https://zany-space-eureka-67rqv5jgj67hr4jw-3001.app.github.dev/api/v1
    ports:
      - '3000:80'
    depends_on:
      - blog-backend
